version: 2
updates:
  # Backend Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "backend"
      - "security-review-required"
    reviewers:
      - "backend-leads"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      testing-libraries:
        patterns:
          - "jest*"
          - "@testing-library/*"
    ignore:
      - dependency-name: "typescript"
        versions: ["6.x"]
    open-pull-requests-limit: 10

  # Frontend Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "frontend"
      - "security-review-required"
    reviewers:
      - "frontend-leads"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
      mui:
        patterns:
          - "@mui/*"
      testing-libraries:
        patterns:
          - "@testing-library/*"
    ignore:
      - dependency-name: "typescript"
        versions: ["6.x"]
    open-pull-requests-limit: 10

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "ci"
      - "security-review-required"
    reviewers:
      - "devops-team"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    open-pull-requests-limit: 5