/**
 * @fileoverview Centralized error code definitions and HTTP status codes for the MGA Operating System.
 * Provides standardized error handling across the application with typed enums and constants.
 * @version 1.0.0
 */

/**
 * Standard HTTP status codes used across the application
 */
export enum HTTP_STATUS_CODES {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  CONFLICT = 409,
  UNPROCESSABLE_ENTITY = 422,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504
}

/**
 * Application-specific error codes with insurance industry context
 */
export enum ERROR_CODES {
  VALIDATION_ERROR = 'ERR_VALIDATION',
  AUTHENTICATION_ERROR = 'ERR_AUTH',
  AUTHORIZATION_ERROR = 'ERR_FORBIDDEN',
  NOT_FOUND_ERROR = 'ERR_NOT_FOUND',
  SYSTEM_ERROR = 'ERR_SYSTEM',
  INTEGRATION_ERROR = 'ERR_INTEGRATION',
  BUSINESS_RULE_ERROR = 'ERR_BUSINESS_RULE',
  DUPLICATE_ERROR = 'ERR_DUPLICATE',
  RATE_LIMIT_ERROR = 'ERR_RATE_LIMIT',
  DATA_INTEGRITY_ERROR = 'ERR_DATA_INTEGRITY',
  CONFIGURATION_ERROR = 'ERR_CONFIG',
  EXTERNAL_SERVICE_ERROR = 'ERR_EXTERNAL_SERVICE',
  POLICY_VALIDATION_ERROR = 'ERR_POLICY_VALIDATION',
  UNDERWRITING_ERROR = 'ERR_UNDERWRITING',
  BILLING_ERROR = 'ERR_BILLING',
  DOCUMENT_ERROR = 'ERR_DOCUMENT'
}

/**
 * User-friendly error messages mapped to error codes
 */
export const ERROR_MESSAGES: Record<ERROR_CODES, string> = {
  [ERROR_CODES.VALIDATION_ERROR]: 'Request validation failed. Please check input data.',
  [ERROR_CODES.AUTHENTICATION_ERROR]: 'Authentication failed. Please verify credentials.',
  [ERROR_CODES.AUTHORIZATION_ERROR]: 'Access denied. Insufficient permissions.',
  [ERROR_CODES.NOT_FOUND_ERROR]: 'Requested resource not found.',
  [ERROR_CODES.SYSTEM_ERROR]: 'Internal server error occurred. Please try again later.',
  [ERROR_CODES.INTEGRATION_ERROR]: 'External service integration failed.',
  [ERROR_CODES.BUSINESS_RULE_ERROR]: 'Operation violates business rules.',
  [ERROR_CODES.DUPLICATE_ERROR]: 'Resource already exists.',
  [ERROR_CODES.RATE_LIMIT_ERROR]: 'Rate limit exceeded. Please try again later.',
  [ERROR_CODES.DATA_INTEGRITY_ERROR]: 'Data integrity constraint violation.',
  [ERROR_CODES.CONFIGURATION_ERROR]: 'System configuration error.',
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 'External service unavailable.',
  [ERROR_CODES.POLICY_VALIDATION_ERROR]: 'Policy validation failed.',
  [ERROR_CODES.UNDERWRITING_ERROR]: 'Underwriting process error.',
  [ERROR_CODES.BILLING_ERROR]: 'Billing operation failed.',
  [ERROR_CODES.DOCUMENT_ERROR]: 'Document processing error.'
};

/**
 * Error severity levels for monitoring and alerting
 */
export enum ERROR_SEVERITY {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  INFO = 'INFO'
}

/**
 * Mapping between application error codes and HTTP status codes
 */
export const ERROR_CODE_HTTP_MAP: Record<ERROR_CODES, HTTP_STATUS_CODES> = {
  [ERROR_CODES.VALIDATION_ERROR]: HTTP_STATUS_CODES.BAD_REQUEST,
  [ERROR_CODES.AUTHENTICATION_ERROR]: HTTP_STATUS_CODES.UNAUTHORIZED,
  [ERROR_CODES.AUTHORIZATION_ERROR]: HTTP_STATUS_CODES.FORBIDDEN,
  [ERROR_CODES.NOT_FOUND_ERROR]: HTTP_STATUS_CODES.NOT_FOUND,
  [ERROR_CODES.SYSTEM_ERROR]: HTTP_STATUS_CODES.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.INTEGRATION_ERROR]: HTTP_STATUS_CODES.BAD_GATEWAY,
  [ERROR_CODES.BUSINESS_RULE_ERROR]: HTTP_STATUS_CODES.UNPROCESSABLE_ENTITY,
  [ERROR_CODES.DUPLICATE_ERROR]: HTTP_STATUS_CODES.CONFLICT,
  [ERROR_CODES.RATE_LIMIT_ERROR]: HTTP_STATUS_CODES.TOO_MANY_REQUESTS,
  [ERROR_CODES.DATA_INTEGRITY_ERROR]: HTTP_STATUS_CODES.UNPROCESSABLE_ENTITY,
  [ERROR_CODES.CONFIGURATION_ERROR]: HTTP_STATUS_CODES.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: HTTP_STATUS_CODES.BAD_GATEWAY,
  [ERROR_CODES.POLICY_VALIDATION_ERROR]: HTTP_STATUS_CODES.UNPROCESSABLE_ENTITY,
  [ERROR_CODES.UNDERWRITING_ERROR]: HTTP_STATUS_CODES.UNPROCESSABLE_ENTITY,
  [ERROR_CODES.BILLING_ERROR]: HTTP_STATUS_CODES.UNPROCESSABLE_ENTITY,
  [ERROR_CODES.DOCUMENT_ERROR]: HTTP_STATUS_CODES.UNPROCESSABLE_ENTITY
};