# Jaeger Helm chart values for MGA OS distributed tracing
# Chart version: jaegertracing/jaeger@2.40.0

# Global settings
global:
  namespace: monitoring
  serviceAccount: jaeger

# Collector configuration
collector:
  replicas: 2
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  persistence:
    enabled: true
    storageClass: gp2
    size: 50Gi
  sampling:
    default: 1
    rules:
      - service: mga-os-backend
        type: probabilistic
        param: 1.0
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname

# Storage configuration using Elasticsearch
storage:
  type: elasticsearch
  options:
    es:
      server-urls: http://elasticsearch-master:9200
      username: elastic
      index-prefix: jaeger
      tls:
        enabled: true
        ca: /etc/jaeger/certificates/ca.crt
      num-shards: 5
      num-replicas: 1
      max-doc-count: 20000000

# Query service configuration
query:
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    hosts:
      - jaeger.mga-os.internal
    tls:
      - secretName: jaeger-tls
        hosts:
          - jaeger.mga-os.internal
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname

# Agent configuration
agent:
  strategy: DaemonSet
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

# Prometheus ServiceMonitor configuration
serviceMonitor:
  enabled: true
  namespace: monitoring
  selector:
    matchLabels:
      app: jaeger
  endpoints:
    - port: admin-http
      path: /metrics
      interval: 30s
      scrapeTimeout: 25s
  metricRelabelings:
    - sourceLabels: ["__name__"]
      regex: jaeger_.*
      action: keep

# Network policies
networkPolicy:
  enabled: true
  ingressPolicies:
    - from:
        - namespaceSelector:
            matchLabels:
              name: mga-monitoring
      ports:
        - port: 9090
          protocol: TCP

# Security settings
security:
  tls:
    enabled: true
    ca: /etc/jaeger/certificates/ca.crt
  authentication:
    enabled: true
    type: oauth2
  authorization:
    enabled: true
    type: rbac

# Retention settings
retention:
  schedule: "0 0 * * *"
  maxAge: 7d
  enabled: true